# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99abc46199894fb5b3d65654ae93861987a50cbbb0cef37312b87f1e51f06c40f9ba0b5917d931c6b3cd20c3c8473fb6f6eb16e777a71db5f5905e580823659a

test:
  secret_key_base: 7e5cf1e0de618558b2ffc7dc0c9dee0c3d2f7a69bb210917a8fd4b48033541f861449e9e8beec3c6285b265c4310e125592479e0aef005d9d0756c2b40949d3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
